config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  resources :tribes
  resources :memberships, only: [:create, :destroy]
  
  root to: 'static_pages#home'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/membership.rb
class Membership < ActiveRecord::Base
   attr_accessible :user_id, :tribe_id
   belongs_to :user
   belongs_to :tribe
   

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :image, :tribe_id
  belongs_to :user

  
  mount_uploader :image, ImageUploader
  
  validates :user_id, presence: true
  validates :content, length: { maximum: 1000 }
  
  default_scope order: 'posts.created_at DESC'
  
end

app/models/tribe.rb
class Tribe < ActiveRecord::Base
  attr_accessible :content, :user_id, :name
  
  has_many :memberships
  has_many :users, :through => :memberships
  
  def feed
    Post.scoped(:joins => {:user => :memberships}, :conditions => { :memberships => { :tribe_id => id } })
  end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :name, :email, :password, :password_confirmation, :image
  has_secure_password
  has_many :posts, dependent: :destroy
  
  has_many :memberships
  has_one :tribe, :through => :memberships
  
  mount_uploader :image, ImageUploader
  
  before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token
  
  validates :name,  presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end                
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

   def new
    @membership = Membership.new
   end
   
   def create
      @membership = current_user.memberships.build(params[:membership])
      if @membership.save
        flash[:success] = "Joined!"
        redirect_to root_path
      else
        render 'static_pages/home'
      end
    end

    def update
      @membership.destroy
      redirect_to current_user
    end

    private

      def correct_user
        @membership = current_user.tribes.find_by_id(params[:id])
        redirect_to root_path if @tribe.nil?
      end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user, only: :destroy
  
  def create
    @post = current_user.posts.build(params[:post])
    if @post.save
      flash[:success] = "Post created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def destroy
    @post.destroy
    redirect_to current_user
  end
  
  private
  
    def correct_user
      @post = current_user.posts.find_by_id(params[:id])
      redirect_to root_path if @post.nil?
    end
  
end  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or root_path
    else  
      flash.now[:error] = "Invalid Email/password combination"
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @post = current_user.posts.build if signed_in?
  end

  def help

  end
  
  def about
  end
  
  def contact
  end
   
   
end

app/controllers/tribes_controller.rb
class TribesController < ApplicationController
  
  before_filter :signed_in_user
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy
  
  def index
    @tribes = Tribe.all
  end
  
  def user
    @user = User.find(params[:id])
  end
  
  
  def show
    @tribe = Tribe.find(params[:id])
  end
  
  def new
    @tribe = Tribe.new
  end
  
  def create
    @tribe = Tribe.new(params[:tribe])
    @tribe.users << current_user
    if @tribe.save
      flash[:success] = "Successfully created tribe."
      redirect_to root_path
    else
      render :action => 'new'
    end
  end
  
  def edit
    @tribe = Tribe.find(params[:id])
  end
  
  def update
    @tribe = Tribe.find(params[:id])
    if @tribe.update_attributes(params[:tribe])
      flash[:notice] = "Successfully updated tribe."
      redirect_to @tribe
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @tribe = Tribe.find(params[:id])
    @tribe.destroy
    flash[:notice] = "Successfully destroyed tribe."
    redirect_to tribes_url
  end
  
  private
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end
  
    def admin_user
      redirect_to root_path unless current_user.admin?
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update]
  before_filter :admin_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
  end  
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Sali.sh!"
      redirect_to root_path
    else    
      render 'new'
    end
  end
  
  def edit

  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      sign_in @user
      flash[:success] = "Profile updated"
      redirect_to @user
    else  
      render 'edit'
    end  
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to users_path
  end
  
  
  private
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end
  
  def admin_user
    redirect_to root_path unless current_user.admin?
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = 'Sali.sh'
    if page_title.empty?
      base_title
    else  
      "#{base_title} | #{page_title}"
    end
  end
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def current_user?(user)
    user == current_user 
  end
    
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravator for the given user.
  def gravatar_for(user, options = { size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Sali.sh</a>
  </small>
  <nav>
	<ul>
		<li><%= link_to "About", about_path %></li>
	</ul> 
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">	
		<div class="container-fluid">
			<%= link_to "Sali.sh", root_path, id: "logo"%>
				
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
				    <span class="icon-bar"></span>
				    <span class="icon-bar"></span>
				</a>
				
				<div class="nav-collapse">
				
				<ul class="nav pull-right">
					<li><%= link_to "Home", 	root_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Tribe", users_path %></li>
						<li id="fat-menu" class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>	
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
							</ul>
							
					<% else %>
					<li><%= link_to "Sign in", 	signin_path %></li>
					<% end %>
					
				</ul>
			</div>
		</div>	
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<link type="text/css" rel="stylesheet" href="https://fast.fonts.com/cssapi/96aa841b-f394-4873-b311-7d94a25b1a66.css"/>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container-fluid">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>			
	  		<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/memberships/new.html.erb
<% provide(:title, "Join Tribe")%>


<div class="formcenter">
			<%= form_for(@membership) do |f| %>
				<%#= render 'shared/error_messages', object: @user %>	
				<%#= f.collection_select ("post", "category", Post::CATEGORIES, {:include_blank => true}) %>
				<%= f.label :tribe_id %>
				<%= f.text_field :tribe_id %>
				
				<%= f.submit "Join Tribe", class: "btn btn-large btn-primary"%>
	
			<% end %>
			
			<p>Already a member? <%= link_to "Sign in", signin_path %></p>

</div>

app/views/posts/_post.html.erb
<li>
	<span class="image"><%= image_tag post.image_url.to_s if post.image? %></span>
	<section>
	<span class="content"><%= post.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(post.created_at) %> ago
	</span>
	<% if current_user?(post.user) %>
		<%= link_to "delete", post, method: :delete,
									confirm: "You sure?", 
									title: post.content %>
	<% end %>
	</section>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
		the form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>		
<% end %>	

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
	<%= render 'shared/error_messages', object: @post %>
	<div class="field" style="border-top: 1px solid #EAEAEA; padding:10px">
		<%= f.label :image %>
		<%= f.file_field :image %>
		<%= f.text_area :content, placeholder: "Text...", class: "compose" %>
	</div>
	<%= f.submit "Post", class: "btn btn-large btn-primary"%>	
<% end %>	

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 150 %>
</a>
<h1 style="text-align: right; margin: 8px;"><%= current_user.name %></h1>
<h4 style="text-align: right"><%= link_to "view posts", current_user %></h4>
<h4 style="text-align: right; padding-top: 5px"><%= pluralize(current_user.posts.count, "Post") %></h4>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us')%>
<h1>About Us</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact')%>
<h1>Contact</h1>
<p>this is the stuff</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
<h1>Feed</h1>
<div class="row-fluid">
<div class="span8">
		<ol class="posts">
			<%= render partial: 'shared/feed_item', collection: @feed_items %>
		</ol>
</div>
</div>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<div class ="row-fluid">
		<div class="span4">
			<section style="margin-bottom: 15px">
			<%= render 'shared/user_info' %>
			</section>
		</div>
		<div class="span8">		
			<%= render 'shared/post_form' %>
		</div>
	</div>
<% else %>  
	<div class ="center hero-unit">
		<h1>Less is More.</h1>
		<p>Welcome to Salish.</p>

		<%= link_to "sign up now", signup_path, class: "btn btn-large btn-primary"%>
	</div>
<% end %>

app/views/tribes/index.html.erb
<% provide(:title, 'All Tribes') %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for tribe in @tribes %>
    <tr>
      <td><%= link_to tribe.name, tribe %></td>
	
	<% if current_user.admin? && !current_user?(tribe) %>
	

      <td><%= link_to "Edit", edit_tribe_path(tribe) %></td>
	<td><%= link_to "delete", tribe, method: :delete, confirm: "You sure?" %></td>
	<% end %>
    </tr>
  <% end %>
</table>

<p><%#= link_to "New Group", new_group_path %></p>

app/views/tribes/new.html.erb
<% provide(:title, "New Tribe")%>
<h1>New Tribe</h1>

<div class="formcenter">
			<%= form_for(@tribe) do |f| %>
				<%#= render 'shared/error_messages', object: @user %>	
				<%= f.label :name %>
				<%= f.text_field :name %>
	
				<%= f.submit "Start Tribe", class: "btn btn-large btn-primary"%>
	
			<% end %>
			
			<p>Already a member? <%= link_to "Sign in", signin_path %></p>

</div>

app/views/tribes/show.html.erb
<% provide(:title, @tribe.name) %>
<ul>
<% for user in @tribe.users %>
<li><%=h user.name %></li>

</ul>

<%= render @tribe.feed  %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
	| <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user")%>
<h1>Update your profile</h1>

<div class="formcenter">
	<div class="row">
		<div class="span4">
			<%= form_for(@user, :html => { :multipart =>true }) do |f| %>
				<%= render 'shared/error_messages', object: @user %>	
				<%= f.label :name %>
				<%= f.text_field :name %>
	
				<%= f.label :email %>
				<%= f.text_field :email %>
	
				<%= f.label :password %>
				<%= f.password_field :password%>
	
				<%= f.label :password_confirmation, "Confirm Password" %>
				<%= f.password_field :password_confirmation %>
				
				<%= f.label :image, "Image" %>
				<%= f.file_field :image %>

				<%= f.submit "Save changes", class: "btn btn-large btn-primary"%>
	
			<% end %>
			<%= gravatar_for @user %>
			<a href="http://gravatar.com/emails" target="blank">change</a>
		</div>	
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users')%>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up")%>
<h1>Sign up</h1>

<div class="formcenter">

			<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages', object: @user %>	
				<%= f.label :name %>
				<%= f.text_field :name %>
	
				<%= f.label :email %>
				<%= f.text_field :email %>
	
				<%= f.label :password %>
				<%= f.password_field :password%>
	
				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation %>
	
				<%= f.submit "Create my account", class: "btn btn-large btn-primary"%>
	
			<% end %>
			<p>Already a member? <%= link_to "Sign in", signin_path %></p>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row-fluid">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user, size: 100 %>
				<%= @user.name %>	
			</h1>
			<% if @user.posts.any? %>
				<h3 style="text-align: right">Posts (<%= @user.posts.count %>)</h3>
		</section>
	</aside>
	<div class="span8">
			<ol class="posts">
				<%= render @posts %>
			</ol>
			<%= will_paginate @posts %>
		<% end %>
	</div>
</div>